Reverse string for correct order
rev_str() can reverse input string.Use rev_str() in fib_num_to_str()
to reverse the string which is reversed when transfered to string from
number.Fianlly, the string representing fibonacci number will be read
by client with buf and print buf instead of sz.

In fibdrv.c,delete the line "#include <asm/uaccess.h>" since an error
occures suddenly in this commit.This error is:

./arch/x86/include/asm/uaccess.h:30:27: error: unknown type name
'mm_segment_t'; did you mean 'apm_event_t'?
static inline void set_fs(mm_segment_t fs)
		                  ^~~~~~~~~~~~
						  apm_event_t

This header is for copy_to_user(), but when not including the header,
the program can still run.I don't know what happened for that.